version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo Initializing environment
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain unicorns --domain-owner 664418974749 --query authorizationToken --output text`
  build:
    commands:
      - cd unicorn-web-project
      - echo Build started on `date`
      - mvn -s settings.xml compile
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn -s settings.xml package
artifacts:
  files:
    - unicorn-web-project/target/unicorn-web-project.war
    - unicorn-web-project/appspec.yml
    - unicorn-web-project/scripts/**/*
  discard-paths: no